<a href="https://colab.research.google.com/github/Danilov-Aleksandr/library/blob/master/refinfo_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

Сначала необходимо импортировать библиотеку:

In [1]:
import numpy as np

###Arrays

Numpy массив это матрица значений, одного типа и у каждого значения есть свой индекс, котороый не может быть отрицательным. Так же у каждой матрицы есть форма (shape), которая указывает сколько измерений у нашей матрицы.


Мы можем создать массив из обычного Python листа:

In [2]:
a = np.array([1, 2, 3])  # Создадим вектор
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Попробуем поменять один из элементов вектора
print (a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # Создадим матрицу 
print (b)

[[1 2 3]
 [4 5 6]]


In [4]:
print (b.shape)                 
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy так же предоставляет несколько функций для создания массивов:


In [5]:
a = np.zeros((2,2))  # Создает массив из нулей
print (a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))   # Создает массив из единиц
print (b)

[[1. 1.]]


In [7]:
c = np.full((2,2), 7) # Создает массив, заполненный опредленным числом
print (c) 

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2)        # Создает единичную матрицу размерностью 2х2
print (d)

[[1. 0.]
 [0. 1.]]


In [9]:
e = np.random.random((2,2)) # Создает матрицу указанной размерности, заполненную случайными значениями от 0 до 1.
print (e)

[[0.10626386 0.48726535]
 [0.66421031 0.80467092]]


###Индексация массивов

Numpy предоставляет несколько способов индексации массивов.

Срезы: Аналогично обычным Python спискам, от numpy массивов могут быть взяты 
срезы. Так как массивы могут быть многомерными, необходимо указывать границы среза для каждого измерения.

In [10]:
import numpy as np

# Создадим двумерный массив размерностью (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Используя срезы, получим подмассив, состоящий из первых  2 строк
# и столбцов 1 и 2; полученный массив будет иметь размерность (2, 2):
# Напоминаю, что нумерация в python начинается с 0.
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

[[2 3]
 [6 7]]


Срез - это часть массива, поэтому если мы изменим данные в срезе, то и исходный массив изменится.

In [11]:
print (a[0, 1] ) 
b[0, 0] = 77    # b[0, 0] это тоже самое что и a[0, 1]
print (a[0, 1]) 

2
77


Также можно комбинировать индексацию и срезы:

In [12]:
# Снова создадим матрицу размерностью (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Рассмотрим различные способы создания срезов:


In [13]:
row_r1 = a[1, :]     
row_r2 = a[1:2, :]  
row_r3 = a[[1], :]  
print (row_r1, row_r1.shape) 
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [14]:
# Аналогично можно сделать и со строками:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Срез является частью исходного массива. Но вы можете использовать значения исходного массива для создания нового массива.

In [15]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Рассмотрим пример
# Получим массив размерностью (3, ) 
print (a[[0, 1, 2], [0, 1, 0]])

# выражение выше можно записать немного по-другому
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [16]:
# Можно использовать один и тот же элемент несколько раз
print (a[[0, 0], [1, 1]])

# Перепишем выражение выше иначе.
print (np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


Рассмотрим один полезный трюк с индексацией массивов: выбор или изменение одного элемента в каждой строке матрицы:

In [17]:
# Создадим новый массив
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# Создадим массив из индексов
b = np.array([0, 2, 0, 1])

#Выберем один элемент из каждой строки согласно массиву b
print (a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [19]:
# Так же можно изменять элементы массива
a[np.arange(4), b] += 10
print (a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Рассмотрим индексацию по булевым значениям. Позволяет выбрать только те элементы массива, которые удовлетворяют каким - либо требованиям.

In [20]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Найдем все элементы массива которые больше 2;
                    # получаем массив такой же размерности,
                    # но состоящий из булевых значений,
                    # показывающих удовлетворяет ли элемент условию или нет

print (bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [21]:
# Теперь можно создать подмассив из значений, которые удовлетворяли нашему условию
print (a[bool_idx])

# А вот как можно это сделать быстрее и удобнее
print (a[a > 2])

[3 4 5 6]
[3 4 5 6]


Это только самые основы индексации и срезов. Для получения более глубоких знаний необходимо обратиться к документации.

###Типы данных

Каждый массив состоит из данных одного типа. Numpy предоставляет большой выбор типов данных, из которых можно создать массив. Numpy всегда будет пытаться угадать какой тип вы хотите использовать, но функции которые создают массивы так же принимают в качестве аргумента тот тип, который вам нужен. Рассмотрим на примере:

In [22]:
x = np.array([1, 2])  # Позволим numpy самому выбрать тип данных
y = np.array([1.0, 2.0])  # Позволим numpy самому выбрать тип данных
z = np.array([1, 2], dtype=np.int64)  # Укажем определенный тип данных

print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


Прочесть про все типы данных можно в [документации](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Математика массивов

Так делается поэлементное сложение массивов:

In [23]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print (x + y)
print (np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [24]:
# Поэлементное вычитание
print (x - y)
print (np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [25]:
# Поэлементное умножение
print (x * y)
print (np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [26]:
# Поэлементное деление
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
# Поэлементное извлечение корня
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Для получения произведения вектора на матрицу, или векторов используем отдельную фукнцию:

In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Разные способы получения произведения
print (v.dot(w))
print (np.dot(v, w))

219
219


In [29]:
# Матрица/вектор 
print (x.dot(v))
print (np.dot(x, v))

[29 67]
[29 67]


In [30]:
# Матрица на матрицу
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy предлагает много различных полезных функций для работы над матрицами, например `sum`:

In [31]:
x = np.array([[1,2],[3,4]])

print (np.sum(x))  # Сумма всех элементов матрицы - "10"
print (np.sum(x, axis=0))  # Сумма всех элементов каждого столбца "[4 6]"
print (np.sum(x, axis=1))  # Сумма всех элементов каждой строки "[3 7]"

10
[4 6]
[3 7]


Ознакомиться со всеми фукциями можно в [документации](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Помимо математических операций над матрицами, также часто приходится совершать различные преобразования с матрицами, например, изменить их размерность или транспонировать:

In [32]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [33]:
v = np.array([[1,2,3]])
print (v) 
print (v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


###Broadcasting

Broadcasting - мощный механизм, благодаря которому Numpy может работать с матрицами разных размеров. Часто у нас есть маленький и большой массивы, и мы хотим использовать маленький массив для совершения операций с большим

Например, мы хотим добавить вектор к каждой строке матрицы. Это можно сделать так:

In [34]:
# Добавим вектор v к каждой строке матрицы x,
# сохраним результат в переменную y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Создадим пустой массив той же формы что и x

# Добавим вектор к матрице с помощью цикла:
for i in range(4):
    y[i, :] = x[i, :] + v

print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Сработало!; Однако если матрица `x` очень большая, проходить ее с помощью цикла может быть очень медленно. Заметьте, что добавление к каждой строке матрицы `x` вектора 'v' равнозначно созданию матрицы `vv`, расположив 2 вектора `v` рядом вертикально, затем сделать поэлментное сложение `x` и `vv`. Давайте реализуем этот подход:

In [35]:
vv = np.tile(v, (4, 1))  # Расположим 4 копии вектора V рядом
print (vv)                 # Получим "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [36]:
y = x + vv  # Сложим х и vv
print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Теперь давайте посмотрим на силу broadcasting. Нам необязательно создавать вектор vv чтобы сделать сложение x и v:

In [37]:
import numpy as np

# Добавим вектор v к каждой строке матрицы x,
# сохраним результат в переменную y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # BROADCASTING
print (y) # сравните результат с вычислением в цикле на пару ячеек выше

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Подробнее про broadcasting прочитайте тут: https://pyprog.pro/broadcasting.html 



Broadcasting обычно работает очень быстро, поэтому старайтесь использовать его постоянно (при необходимости конечно)

Это было небольшое введение в Numpy, но это, конечно же, далеко не все. На семинаре мы рассмотрим наиболее частые случаи, когда Numpy нужен в реальных кейсах, и порешаем задачки.

# Фишки с семинара


In [38]:
# найти индекс максимального значения в одномерном массиве:
a = np.array([0.2, 0.4, -0.1, 0.5, 0.33, 0.9, 0.875, 0.14])
np.argmax(a)

5

Формула Z - масштабирования. Где где X - среднее значение, S - стандартное отклонение вычисленные для множества данных x
![Замещающий текст](https://wikimedia.org/api/rest_v1/media/math/render/svg/3fae59e6af64fb5c102229fcf9034175bec85372)

In [39]:
#создать 5х5 массив из рандомных значений и сделать Z-масштабирование
Z = np.random.random((5,5))
(Z - np.mean(Z) )/ np.std(Z)

array([[-1.52186766, -0.50252179,  0.71992701, -0.71333174,  1.1912092 ],
       [-0.10200421,  1.11106061,  2.04696076,  1.3810406 ,  0.41489899],
       [ 0.18333881, -0.94747718, -0.61682636,  1.54151834, -1.25632811],
       [-1.36910666,  0.37460486,  0.87069727, -0.67012583, -1.23446862],
       [-0.56135653,  0.1145157 ,  0.22522588, -1.30123734,  0.62165402]])

In [40]:
#сделать все значения меньше 0 равными 0, а больше 10 равными 10
a = np.random.randint(-2, 12, (4,5))
np.clip(a, 0, 10)

array([[ 4,  6,  6,  2,  7],
       [ 9,  0,  9,  9,  4],
       [ 9,  0,  0,  1,  2],
       [10,  0,  0,  5,  0]])

In [41]:
#представим что у вас есть ч/б картинка размером 28x28, нужно добавить количество каналов = 1
image = np.random.random(784).reshape(28,28)
image_with_channel = image.reshape(28,28,1)
image_with_channel.shape


(28, 28, 1)

In [42]:
#как одной функцией удалить сразу все единичные размерности
a = np.random.random(784).reshape(1,1,28,1,1,28)
a.squeeze().shape

(28, 28)

In [43]:
#создайте нулевой массив по форме другого:
a = np.arange(10).reshape(5,2)

labels = np.zeros_like(a)
labels

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [44]:
#Напишем фукнцию активации. Возьмем сигмоиду.
def sigmoid(x):
    return 1/(1+np.exp(-x))



In [45]:
#создайте 2 numpy array: один для входов, другой для выходов

# набор входных данных
X = np.array([  [0,0,1],
                [1,1,1],
                [1,0,1],
                [0,1,1] ])
    
# выходные данные            
y = np.array([[0,1,1,0]]).T


# Установим сид, для лучшей воспроизводимости экспериментов
np.random.seed(42)

# инициализируем веса случайным образом со средним 0 в диапозоне [-1, 1]
weights = 2*np.random.random((3,1)) - 1


print(weights)

[[-0.25091976]
 [ 0.90142861]
 [ 0.46398788]]


In [46]:
inputs = X
outputs = sigmoid(np.matmul(X, weights))
print(outputs)

[[0.61395979]
 [0.75296649]
 [0.55306642]
 [0.79663861]]


In [47]:
for iter in range(20000):
    # прямое распространение
    inputs = X
    outputs = sigmoid(np.matmul(inputs, weights))

    # насколько мы ошиблись?
    error = y - outputs
    
    #Магия градиентов (будет понятнее после следующего занятия, пока примите это как есть)
    #можно объяснить пробек пропагейшн если есть желание
    delta = error * (outputs * (1-outputs))
    adjust = np.matmul(inputs.T, delta)

    # обновим веса
    weights = weights +  adjust

#Проверим результаты
print ("Выходные данные после тренировки:")
print (outputs)


Выходные данные после тренировки:
[[0.00679799]
 [0.99445494]
 [0.99548505]
 [0.00553642]]
